name: Setup repository environment
description: Checkout code, install uv, setup Python, sync dependencies, and install Bun.
inputs:
  ref:
    description: Optional git ref to checkout.
    required: false
    default: ''
  python-version:
    description: Python version to install with uv.
    required: false
    default: '3.14'
  sync-args:
    description: Additional arguments passed to `uv sync`.
    required: false
    default: '--all-extras --frozen'
  bun-version:
    description: Bun version to install.
    required: false
    default: latest
  uv-cache:
    description: Whether to enable uv caching.
    required: false
    default: 'true'
  bun-cache:
    description: Whether to enable Bun cache reuse.
    required: false
    default: 'true'
  biome-cache:
    description: Whether to enable Biome cache reuse.
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref }}
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: ${{ inputs.uv-cache }}
    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: uv sync ${{ inputs.sync-args }}
    - name: Cache Bun downloads
      if: ${{ inputs.bun-cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          ~/.bun/install/global
        key: bun-${{ runner.os }}-${{ hashFiles('package-lock.json', 'bunfig.toml') }}
        restore-keys: |
          bun-${{ runner.os }}-
    - name: Cache Biome
      if: ${{ inputs.biome-cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/biome
          ~/.cache/biomejs
        key: biome-${{ runner.os }}-${{ hashFiles('biome.json', 'package-lock.json') }}
        restore-keys: |
          biome-${{ runner.os }}-
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
