# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tools namespace exposing the :mod:`weakincentives.tools.api` surface."""

# pyright: reportImportCycles=false

from __future__ import annotations

from . import api
from .api import (
    AddStep,
    AstevalSection,
    ClearPlan,
    DeadlineExceededError,
    DeleteEntry,
    DispatchSubagentsParams,
    EditFileParams,
    EvalFileRead,
    EvalFileWrite,
    EvalParams,
    EvalResult,
    FileInfo,
    GlobMatch,
    GlobParams,
    GrepMatch,
    GrepParams,
    HostMount,
    ListDirectory,
    ListDirectoryParams,
    ListDirectoryResult,
    MarkStep,
    NewPlanStep,
    Plan,
    PlanningStrategy,
    PlanningToolsSection,
    PlanStatus,
    PlanStep,
    PodmanSandboxConfig,
    PodmanSandboxSection,
    PodmanShellParams,
    PodmanShellResult,
    PodmanWorkspace,
    ReadFile,
    ReadFileParams,
    ReadFileResult,
    ReadPlan,
    RemoveParams,
    SetupPlan,
    StepStatus,
    SubagentIsolationLevel,
    SubagentResult,
    SubagentsSection,
    ToolValidationError,
    UpdateStep,
    VfsFile,
    VfsPath,
    VfsToolsSection,
    VirtualFileSystem,
    WorkspaceDigest,
    WorkspaceDigestSection,
    WriteFile,
    WriteFileParams,
    build_dispatch_subagents_tool,
    clear_workspace_digest,
    dispatch_subagents,
    latest_workspace_digest,
    set_workspace_digest,
)

__all__ = [
    "AddStep",
    "AstevalSection",
    "ClearPlan",
    "DeadlineExceededError",
    "DeleteEntry",
    "DispatchSubagentsParams",
    "EditFileParams",
    "EvalFileRead",
    "EvalFileWrite",
    "EvalParams",
    "EvalResult",
    "FileInfo",
    "GlobMatch",
    "GlobParams",
    "GrepMatch",
    "GrepParams",
    "HostMount",
    "ListDirectory",
    "ListDirectoryParams",
    "ListDirectoryResult",
    "MarkStep",
    "NewPlanStep",
    "Plan",
    "PlanStatus",
    "PlanStep",
    "PlanningStrategy",
    "PlanningToolsSection",
    "PodmanSandboxConfig",
    "PodmanSandboxSection",
    "PodmanShellParams",
    "PodmanShellResult",
    "PodmanWorkspace",
    "ReadFile",
    "ReadFileParams",
    "ReadFileResult",
    "ReadPlan",
    "RemoveParams",
    "SetupPlan",
    "StepStatus",
    "SubagentIsolationLevel",
    "SubagentResult",
    "SubagentsSection",
    "ToolValidationError",
    "UpdateStep",
    "VfsFile",
    "VfsPath",
    "VfsToolsSection",
    "VirtualFileSystem",
    "WorkspaceDigest",
    "WorkspaceDigestSection",
    "WriteFile",
    "WriteFileParams",
    "api",
    "build_dispatch_subagents_tool",
    "clear_workspace_digest",
    "dispatch_subagents",
    "latest_workspace_digest",
    "set_workspace_digest",
]


def __dir__() -> list[str]:
    return sorted({*globals().keys(), *__all__})
